### ISSUE TITLE
Roaming issue

### ISSUE THREAD

**Issue by RvV1979** [pietje666/plugin.video.vrt.nu#49]
I am in NL. My vrt account is verified, including Belgian phone number and allows me to stream content from the vrt nu website. However, in the kodi addon, whenever I select a stream I get a message:

`Roaming settings are incomplete, to enable watching geo-blocked content while roaming please add additional information to the user profile`

Can you please advise?

Thanks

**Comment by mediaminister** [comment]
I'll have to investigate this problem.

Can you first test if it works in the previous 1.4.2 version? Uninstall the add-on and than install the previous version from zip file: https://kodi.tv/addon/plugins-video-add-ons/vrt-nu-1

**Comment by RvV1979** [comment]
If I remember correctly, the issue arose after upgrading to 1.5.0. I tried downloading the 1.4.3 zip file but get a `file not found`. Thanks for your assistance.

**Comment by mediaminister** [comment]
I investigated this problem and I made an experimental fix. Source code is at: https://github.com/mediaminister/plugin.video.vrt.nu/commit/c184382fb072c8336c2d820ee9dad1eacf09668f

You can install this experimental fix by installing the following zip file in Kodi:
[plugin.video.vrt.nu.zip](https://github.com/pietje666/plugin.video.vrt.nu/files/2730009/plugin.video.vrt.nu.zip)

Please report if this fix works for you.

**Comment by RvV1979** [comment]
I can confirm that the issue is now resolved. Thank you so much for the support!

**Comment by mediaminister** [comment]
Fine, in the meantime I have tested this fix myself on a Danish VPN and I could not cause a error in Kodi. I made some small changes to provide the user a message when his vrt account has no verified phone number. 
I made a pull request to add this fix to this repository: https://github.com/pietje666/plugin.video.vrt.nu/pull/50

**Comment by RvV1979** [comment]
Hi, I have upgraded to v1.5.2 and the same issue has resurfaced. I am again getting `NOTICE: Roaming settings are incomplete, to enable watching geo-blocked content while roaming please add additional information tot he user profile`. But my profile as used on vrt.nu is still complete and the website does allow me to stream geo-blocked content. 

Downgrading to 1.5.0 using the zip file referenced above fixes the issue. 

Thanks

**Comment by pietje666** [comment]
Yes the issue is already fixed in code. Will be rolled out in the next release!

**Comment by RvV1979** [comment]
OK great - thanks

**Comment by geert-hendrickx-be** [comment]
Hi

I'm trying roaming for the version time and still getting this error.  Plugin version 2.3.2, vrtnu login with verified Belgian phone number.  Debug log is attached.
[kodi.log](https://github.com/add-ons/plugin.video.vrt.nu/files/4432154/kodi.log)

**Comment by dagwieers** [comment]
@geert-hendrickx-be Please open a new issue for this.

**Comment by geert-hendrickx-be** [comment]
Done; https://github.com/add-ons/plugin.video.vrt.nu/issues/721
